# Generated by Django 4.2.30 on 2026-06-27 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_agent_platform_prd_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkDirectory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('worktree_strategy', models.CharField(default='per_task', max_length=40)),
                ('branch_policy', models.JSONField(blank=True, default=dict)),
                ('prd_path', models.CharField(default='prd.md', max_length=512)),
                ('status_path', models.CharField(default='status.md', max_length=512)),
                ('progress_path', models.CharField(default='progress.md', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('default_worker_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_work_directories', to='db.agentworkercard')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_work_directories', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_work_directories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentWorkerMount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('local_path', models.CharField(max_length=512)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_mounts', to='db.agentworkdirectory')),
                ('worker_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_directory_mounts', to='db.agentworkercard')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_worker_mounts', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_worker_mounts',
                'ordering': ('work_directory', 'worker_card__name'),
            },
        ),
        migrations.CreateModel(
            name='AgentWorkDirectoryRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relative_path', models.CharField(default='.', max_length=512)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('worktree_strategy', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_directory_links', to='db.agentrepository')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='db.agentworkdirectory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_work_directory_repositories', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_work_directory_repositories',
                'ordering': ('work_directory', 'sort_order', 'repository__name'),
            },
        ),
        migrations.CreateModel(
            name='AgentTaskWorkDirectoryOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_branch', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_work_directory_override', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_overrides', to='db.agentworkdirectory')),
                ('worker_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_work_directory_overrides', to='db.agentworkercard')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_work_directory_overrides', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_work_directory_overrides',
                'ordering': ('issue__sequence_id',),
            },
        ),
        migrations.CreateModel(
            name='AgentProjectDefault',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_default', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('work_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_defaults', to='db.agentworkdirectory')),
                ('worker_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_defaults', to='db.agentworkercard')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_project_defaults', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_project_defaults',
                'ordering': ('project__name',),
            },
        ),
        migrations.AddConstraint(
            model_name='agentworkermount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('work_directory', 'worker_card'), name='agent_worker_mount_unique_directory_worker'),
        ),
        migrations.AddConstraint(
            model_name='agentworkdirectoryrepository',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('work_directory', 'repository'), name='agent_work_directory_repository_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentworkdirectory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'key'), name='agent_work_directory_unique_key_workspace'),
        ),
    ]
