# Generated by Django 4.2.30 on 2026-06-27 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_agent_work_directories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaskContextDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('prd', 'PRD'), ('status', 'Status')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('body_format', models.CharField(default='markdown', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_context_documents', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_context_documents', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_context_documents',
                'ordering': ('issue', 'document_type'),
            },
        ),
        migrations.CreateModel(
            name='AgentTaskContextDocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('prd', 'PRD'), ('status', 'Status')], max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True)),
                ('body_format', models.CharField(default='markdown', max_length=40)),
                ('change_summary', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('system', 'System')], default='human', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.agenttaskcontextdocument')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_context_document_versions', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_context_document_versions', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_context_document_versions',
                'ordering': ('document', '-version'),
            },
        ),
        migrations.CreateModel(
            name='AgentTaskProgressEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entry_type', models.CharField(choices=[('progress', 'Progress'), ('decision', 'Decision'), ('evidence', 'Evidence'), ('validation', 'Validation'), ('handoff', 'Handoff'), ('feedback', 'Feedback')], default='progress', max_length=40)),
                ('source', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('system', 'System')], default='human', max_length=40)),
                ('body', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('node_key', models.CharField(blank=True, max_length=120)),
                ('run_id', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_task_progress_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_progress_entries', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_progress_entries', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_progress_entries',
                'ordering': ('issue', 'occurred_at', 'created_at'),
                'indexes': [models.Index(fields=['workspace', 'issue', 'occurred_at'], name='agent_task__workspa_a2ff6e_idx'), models.Index(fields=['workspace', 'source'], name='agent_task__workspa_6adfae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agenttaskcontextdocumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('document', 'version'), name='agent_task_context_document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='agenttaskcontextdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'document_type'), name='agent_task_context_document_unique_issue_type'),
        ),
    ]
