# Generated by Django 4.2.30 on 2026-06-27 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_agenttaskcontextdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaskWorkflowInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_key', models.SlugField(default='agent-software-delivery', max_length=120)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(default='Agent software delivery workflow', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], default='active', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'agent_task_workflow_instances',
                'ordering': ('issue__sequence_id',),
            },
        ),
        migrations.CreateModel(
            name='AgentTaskWorkflowNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('intake', 'Intake'), ('agent', 'Agent'), ('agent_review', 'Agent Review'), ('human_review', 'Human Review'), ('merge', 'Merge'), ('human_gate', 'Human Gate'), ('release', 'Release'), ('deploy', 'Deployment'), ('exception', 'Exception'), ('terminal', 'Terminal')], max_length=40)),
                ('owner_type', models.CharField(default='agent', max_length=40)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('conversational', 'Conversational'), ('terminal', 'Terminal')], default='auto', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('main_exits', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_nodes', to='db.agentuseragent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow_nodes', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='db.agenttaskworkflowinstance')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_workflow_nodes', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_workflow_nodes',
                'ordering': ('workflow_instance', 'sort_order'),
            },
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='active_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_workflow_instances', to='db.agenttaskworkflownode'),
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='default_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_task_workflows', to='db.agentuseragent'),
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow_instance', to='db.issue'),
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='agenttaskworkflowinstance',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_workflow_instances', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='AgentTaskWorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approve', 'Approve'), ('return', 'Return'), ('set_auto', 'Set Auto'), ('set_manual', 'Set Manual'), ('block', 'Block'), ('agent_failed', 'Agent Failed')], max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_task_workflow_transitions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transitions', to='db.agenttaskworkflownode')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow_transitions', to='db.issue')),
                ('to_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transitions', to='db.agenttaskworkflownode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='db.agenttaskworkflowinstance')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_workflow_transitions', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_task_workflow_transitions',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['workspace', 'issue', 'created_at'], name='agent_task__workspa_e4ec30_idx'), models.Index(fields=['workspace', 'action'], name='agent_task__workspa_9164af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agenttaskworkflownode',
            index=models.Index(fields=['workspace', 'issue', 'status'], name='agent_task__workspa_3b3835_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttaskworkflownode',
            index=models.Index(fields=['workspace', 'key'], name='agent_task__workspa_aec829_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttaskworkflownode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow_instance', 'key'), name='agent_task_workflow_node_unique_key_instance'),
        ),
        migrations.AddIndex(
            model_name='agenttaskworkflowinstance',
            index=models.Index(fields=['workspace', 'status'], name='agent_task__workspa_a3ecd8_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttaskworkflowinstance',
            index=models.Index(fields=['workspace', 'active_node'], name='agent_task__workspa_5e9463_idx'),
        ),
    ]
